import Footer from "./layout/footer"
import Navigation from "./layout/navigation"
import type { Metadata } from "next"
import Script from "next/script"

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  let lightmode = false

  return (
    <html>
      <head>
        <Script
          src="https://kit.fontawesome.com/cc6c58e096.js"
          crossOrigin="anonymous"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${lightmode ? "light-mode" : ""}`}>
        <Navigation />
        <div className="min-h-[calc(100dvh-106px)]">{children}</div>
        <Footer />
      </body>
    </html>
  )
}
